baseURL = "https://blog.task.media/"
languageCode = "de-DE"
title = "task.media Blog"
theme = "bilberry-hugo-theme"
publishDir = "public"

[params]
	gravatarEMail = "mail@task.media"

	github = "https://github.com/taskmedia"

	copyrightBy = "task.media"
	copyrightUseCurrentYear = true
	copyrightUrl = "https://task.media"
